server:
    error:
        include-message: always
        include-binding-errors: always

spring:
  datasource:
    password: 123456
    url: jdbc:postgresql://localhost:5432/registration
    username: postgres
  jpa:
      hibernate:
#        ddl-auto: create-drop # this recreates the database everytime the application is started
        ddl-auto: update
#        ddl-auto: validate # this is for production
      properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
        show-sql: true